Add an EXCLUDES_LIST param to job generators
AdoptOpenJDK/openjdk-build pull request #2048
Opened 2020-09-02 12:32 UTC by M-Davies

Adds a parameter that allows a user to exclude certain configurations from being regenerated

Closes: #2045 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

2020-09-03 09:27 UTC, M-Davies commented
Tested this with a test generator
- https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/alpha_pipeline_jobs_generator/17/ tests `EXCLUDES_LIST` populated with `{    "x64Mac": [        "hotspot",        "openj9"    ] }`. These platforms were not regenerated as expected
```
10:18:13  [INFO] Regenerating: x64Mac
[Pipeline] echo
10:18:13  [INFO] Regenerating variant x64Mac: hotspot...
[Pipeline] echo
10:18:13  [INFO] FOUND MATCH! buildConfiguration key: x64Mac and config file key: x64Mac
[Pipeline] echo
10:18:13  [INFO] Excluding mac: hotspot from jdk8u regeneration due to it being in the EXCLUDES_LIST...
[Pipeline] echo
10:18:13  [INFO] Regenerating variant x64Mac: openj9...
[Pipeline] echo
10:18:13  [INFO] FOUND MATCH! buildConfiguration key: x64Mac and config file key: x64Mac
[Pipeline] echo
10:18:13  [INFO] Excluding mac: openj9 from jdk8u regeneration due to it being in the EXCLUDES_LIST...
```
- https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/alpha_pipeline_jobs_generator/18/console tests `EXCLUDES_LIST` populated with `{    "x64MacXL": [       "openj9"    ] }`. This platform also was not regenerated as expected:
```
10:26:10  [INFO] Regenerating: x64MacXL
[Pipeline] echo
10:26:10  [INFO] Regenerating variant x64MacXL: openj9...
[Pipeline] echo
10:26:10  [INFO] FOUND MATCH! buildConfiguration key: x64MacXL and config file key: x64MacXL
[Pipeline] echo
10:26:10  [INFO] Excluding mac: openj9 from jdk8u regeneration due to it being in the EXCLUDES_LIST...
```
This is ready for review

2020-09-03 09:27 UTC, M-Davies commented
@AdamBrousseau @andrew-m-leonard Could I get reviews please?

2020-09-03 14:13 UTC, AdamBrousseau reviewed
@M-Davies This is great and will be very useful. However I think it only addresses one part of #2045. If I wanted to generate with a custom config, for example, different node labels or different test suits, I would still have to fork/modify to get what I want. Unless I am missing another feature?

2020-09-03 14:19 UTC, M-Davies commented
@AdamBrousseau See https://github.com/AdoptOpenJDK/openjdk-build/issues/2045#issuecomment-685617366. Those are the two use cases I identified that I thought would be most appropriate to resolve your issue. Short of forking/branching your own config files, I'm not sure how else you could keep in sync. Unless I'm missing something or misunderstanding your issue?

2020-09-08 14:08 UTC, M-Davies commented
run tests

2020-09-09 09:39 UTC, M-Davies commented
run tests

2020-09-10 09:09 UTC, M-Davies commented
@AdamBrousseau Could I get your review please?

2020-09-11 05:08 UTC, AdamBrousseau approved these changes
LFTM. Thanks Morgan.

2020-09-11 15:39 UTC, karianna requested changes
Couple of changs - also does this need to go in before next week's release?  Else it'll have to wait.

2020-09-11 15:39 UTC, karianna commented on pipelines/build/common/config_regeneration.groovy
> +import groovy.json.*
Prefer explicit imports

2020-09-11 15:39 UTC, karianna commented on pipelines/build/common/config_regeneration.groovy
> +                return "EXCLUDED"
Magic string, declare as a const?

2020-09-11 21:26 UTC, M-Davies commented
> Couple of changs - also does this need to go in before next week's release?  Else it'll have to wait.

Unless @AdamBrousseau needs to it be in for the OpenJ9 release, it can wait until afterwards

2020-09-11 23:19 UTC, AdamBrousseau commented
No rush on my side.

2020-09-15 08:54 UTC, karianna commented
@M-Davies I think the comments also need addressing?

2020-09-22 11:18 UTC, M-Davies commented
@karianna They've been addressed. Just waiting for https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/alpha_pipeline_jobs_generator/49/console to finish testing the changes to confirm everyone still works ok. Once it finishes (and hopefully passes), I could use a re-review

2020-09-22 14:01 UTC, karianna approved these changes

2020-09-23 09:01 UTC, tellison approved these changes

2020-09-24 09:33 UTC, gdams approved these changes

2020-09-24 09:33 UTC, merged