Autodetect boot JDK location based on playbook defaults
AdoptOpenJDK/openjdk-build pull request #2167
Opened 2020-10-21 19:46 UTC by sxa

Draft PR to auto-set JDK_BOOT_DIR based on default locations symlinked by the ansible playbooks. This should remove the need to have JDKxx_BOOT_DIR definitions on the build machines in jenkins and reduce the number of times a boot JDK is downloaded dynamically during the builds

[VPC run](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/912/)

Signed-off-by: Stewart X Addison <sxa@redhat.com>

2020-10-22 10:54 UTC, karianna approved these changes
LGTM

2020-10-23 10:35 UTC, sxa commented
Needs more work as it's causing issues in VPC with JDK8 builds using JDK7 to boot
[Working build](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=CentOS6,label=vagrant/905/consoleFull):
```
15:05:06 Detecting boot jdk for: jdk8u
15:05:06 Found build version: 8
15:05:06 Required boot JDK version: 7
15:05:06 /usr/local/gcc/bin/ccache
15:05:06 Boot jdk directory: /usr/lib/jvm/java-1.7.0-openjdk.x86_64:
15:05:07 BOOT JDK: java version "1.7.0_261"
```
[New failing build](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/915/OS=Debian10,label=vagrant/console):
```
14:17:03 Detecting boot jdk for: jdk8u
14:17:03 Found build version: 8
14:17:03 Required boot JDK version: 7
14:17:03 Downloading GA release of boot JDK version 7...
14:17:03 
14:17:03 gzip: stdin: unexpected end of file
14:17:03 tar: Child returned status 1
14:17:03 tar: Error is not recoverable: exiting now
```

2020-10-29 16:36 UTC, AdamBrousseau commented
Could bootjdk location be added to the config files jdkX_pipeline_config.groovy?
I'm thinking if a machine does not use the default playbook locations and the preference is to not have to define the variable on the Jenkins node, then it may be nice to have the option available in the config file (Related #2132).

2021-02-03 11:58 UTC, karianna commented
@sxa  - Did you want to continue with this PR or are you happy to park it given our [refactoring efforts](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1612353108094700)?

2021-02-08 16:57 UTC, sxa commented
> @sxa - Did you want to continue with this PR or are you happy to park it given our [refactoring efforts](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1612353108094700)?

On my list for this week, but I don't believe this PR is part of the stuff that's going to be moved. This will make the build and infra a bit simpler, so I want it in :-)

2021-02-08 17:30 UTC, sxa commented
> Could bootjdk location be added to the config files jdkX_pipeline_config.groovy?

I think a default could reasonably be made there. My interest in particular is making sure that if someone is trying to debug locally on a machine (so not running via the playbooks) that these scripts are as self-sufficient as possible, but I certainly wouldn't be averse to having them in another location too

2021-02-08 17:31 UTC, sxa commented
Not quite certain which VPC platforms are stable at the moment unfortunately so I've run two for this to be able to compare:
- https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1010/ (JDK15 - without this change)
- https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1011/ (JDK15 - with this change)

2021-02-15 16:58 UTC, sxa commented
VPC - [JDK15](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1035/) [JDK8](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1036/)

2021-02-16 14:51 UTC, sxa commented
New vpc after further minor adjustments: [JDK15](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1042) - [JDK8](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1043)

2021-02-16 14:59 UTC, sxa commented
run tests

2021-02-16 17:05 UTC, M-Davies requested changes
Indentations appear off after the removal of the following if block. Might be just GH's editor being funky with tabs however
```bash
# Any version above 8 (11 for now due to openjdk-build#1409
if [ "$JAVA_FEATURE_VERSION" -gt 11 ]; then
```

2021-02-16 17:11 UTC, sxa commented
> Indentations appear off after the removal of the following if block. Might be just GH's editor being funky with tabs however
> 
> ```shell
> # Any version above 8 (11 for now due to openjdk-build#1409
> if [ "$JAVA_FEATURE_VERSION" -gt 11 ]; then
> ```

Can you be more specific with "off"? Looks ok to me
![image](https://user-images.githubusercontent.com/6487691/108097347-eb8a5f80-7079-11eb-8738-34370c7d3839.png)

2021-02-16 17:12 UTC, sxa commented
Oh hang on - you're talking about the AIX one specifically ...

2021-02-16 17:15 UTC, sxa commented
OK I've put the conditional back in for now - adjusting it should probably be the scope of a separate PR

2021-02-16 17:17 UTC, M-Davies commented
All of them actually. If you look at [each file](https://github.com/AdoptOpenJDK/openjdk-build/tree/29f51540a777a481cb0a7f79a460a7088edb77a4/build-farm/platform-specific-configurations) appears off after that if block has been removed. Mac for example:
<img width="673" alt="Screenshot 2021-02-16 at 17 15 48" src="https://user-images.githubusercontent.com/25231953/108098033-cea25c00-707a-11eb-88a2-49a764c0897c.png">

2021-02-16 17:58 UTC, sxa commented
Got stuck in rebase hell there for a bit. Not sure what was going on, anyway hopefully it's ok now and I'm running new VPCs a new vpc after further minor adjustments: [JDK15](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1045) - [JDK8](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1046)

2021-02-16 22:01 UTC, M-Davies approved these changes

2021-02-17 10:07 UTC, gdams approved these changes
Happy for this to go in - I'd like to see someone break this function out into a commonplace though to avoid duplication at some point

2021-02-17 10:42 UTC, sxa commented
> Happy for this to go in - I'd like to see someone break this function out into a commonplace though to avoid duplication at some point

There a lot of cleaning up I'd like to do with these scripts but I'm focusing on usability for now. The directory that it selects is different for each platform which makes it more difficult to get advantages from unifying under a single function (unless we always installed into, day, /usr/local/java regardless of platform

2021-02-17 11:08 UTC, sxa commented
Merging and I'll run a JDK17 pipeline (which failed last night due to the freemarker version issue) in order to verify and fix if required.

2021-02-17 11:09 UTC, merged