Rejig #2175
AdoptOpenJDK/openjdk-build pull request #2202
Opened 2020-11-02 14:45 UTC by M-Davies

* Now will only output metadata on first writeout to prevent duped spam

Follow up to https://github.com/AdoptOpenJDK/openjdk-build/pull/2175
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

2020-11-03 15:13 UTC, karianna approved these changes
LGTM

2020-11-17 12:54 UTC, M-Davies commented
@sxa Can I get your stamp of approval on this one if you're happy with it please? :)

2020-11-18 17:23 UTC, sxa requested changes
@M-Davies Can you make the commit message meaningful please as this shows up in thei repo's history. Somethign like `Adjust conditional for displaying metadata during build` would be better than `rejig`

2020-11-21 15:36 UTC, M-Davies commented
run tests

2020-11-24 13:18 UTC, karianna commented
@sxa - OK now?

2020-11-24 16:59 UTC, sxa approved these changes
Slightly surprised we need two variables metaWrittenOur and initialWrite, but yes I'm ok with it now - thanks for the prod @karianna

2020-11-25 10:22 UTC, merged