add Dragonwell on windows
AdoptOpenJDK/openjdk-build pull request #2243
Opened 2020-11-19 05:57 UTC by joeyleeeeeee97

We could use AdoptOpenJDK pipelines to build Dragonwell on windows.

Dragonwell got a building limitation:

Dragonwell 8 Have to depend on bootstrap
So we may need to pull dragonwell windows release during build.

Also, we need this https://github.com/AdoptOpenJDK/openjdk-build/pull/2232 to build dragonwell on windows.

2020-11-19 12:09 UTC, karianna approved these changes
LGTM - again we need to really split out vendor vs type of VM - maybe we bite the bullet on that refactors in Dec.

2020-11-24 18:25 UTC, M-Davies commented
run tests

2020-11-24 22:55 UTC, M-Davies commented
> # 🟠 PR TESTER RESULT 🟠
> ❎ Some pipelines failed or the job was aborted! ❎
> _See the `pipeline-build-check` below for more information..._

Existing unrelated problems with sign jobs. Running again since the fix has been merged...

run tests

2020-11-25 08:24 UTC, M-Davies commented
> # 🟠 PR TESTER RESULT 🟠
> ❎ Some pipelines failed or the job was aborted! ❎
> _See the `pipeline-build-check` below for more information..._

Unrelated issues

2020-11-25 08:24 UTC, M-Davies approved these changes

2020-11-25 20:21 UTC, karianna commented
Merge conflicts

2020-11-25 21:07 UTC, sxa commented
Hmm hadn't realised it had to bootstrap with a Dragonwell 8 - I hit an issue with that when trying to build on Linux with GCC9 for one of the other issues (We don't seem to make it available in the non-docker build case on Linux/x64 at the moment) :-)

2020-11-25 21:11 UTC, sxa reviewed
Hmm hadn't realised it had to bootstrap with a Dragonwell 8 - I hit an issue with that when trying to build on Linux with GCC9 for one of the other issues (We don't seem to make it available in the non-docker build case on Linux/x64 at the moment) :-)

Why was `checkAndDownloadDragonwellBootstrapWindowsImage` put into `prepareWorkspace.sh` instead of having it added to the ansible scripts on each machine (so as not to download it each time, which is what we do with the other boot JDKs?

2020-11-26 03:13 UTC, joeyleeeeeee97 commented
> Hmm hadn't realised it had to bootstrap with a Dragonwell 8 - I hit an issue with that when trying to build on Linux with GCC9 for one of the other issues (We don't seem to make it available in the non-docker build case on Linux/x64 at the moment) :-)
> 
> Why was `checkAndDownloadDragonwellBootstrapWindowsImage` put into `prepareWorkspace.sh` instead of having it added to the ansible scripts on each machine (so as not to download it each time, which is what we do with the other boot JDKs?

Yes. If it's the same image we do not need to download it over and over again. We could check if it is already downloaded.
If we download the image into the machine, I wonder where could I find the scripts for initiating machines?

2020-12-01 12:38 UTC, joeyleeeeeee97 commented
@sxa  https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1727 I added these to ansible but I don't know how to trigger "playbook changes run through VPC or QPC (if you have access)" for tests. 
Could you give the current code another look and help me trigger the tests?

2020-12-09 03:22 UTC, joeyleeeeeee97 commented
Maybe we could hold this before https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1749, since the downloaded URL is hardcoded may affect this patch.

2020-12-09 14:19 UTC, sxa requested changes
I'd rather cover all the settings of the bootstrap within `windows.sh` if possible instead of doing it via `build.sh`. Also can we rename `DRAGONWELL_BOOTSTRAP` to `DRAGONWELL8_BOOTSTRAP` to make it clear to anyone reading the script that it is only used for JDK8 and not all dragonwell versions (It's clear when you look at this PR, but probably not for someone looking just at windows.sh in the future)

2020-12-09 14:25 UTC, sxa commented
@joeyleeeeeee97 Just a quick note to say that after the playbook change is merged we'll need to ensure that the playbook updates are deployed on all build systems (Something my team will do!) before merging and running this change.

2020-12-10 05:13 UTC, joeyleeeeeee97 commented
> @joeyleeeeeee97 Just a quick note to say that after the playbook change is merged we'll need to ensure that the playbook updates are deployed on all build systems (Something my team will do!) before merging and running this change.

I moved all related changes to `windows.sh`.

http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-dragonwell/29/console
And I tried a build with an image installed at '/cygdrive/C/openjdk/dragonwell-bootstrap/jdk8u272-ga' and that seems to work. Please check again with https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1749. Thanks for your help

2020-12-17 10:33 UTC, karianna commented
OK since the requested changes have been made I'll merge this in @sxa's absence.

2020-12-17 10:33 UTC, merged