Revert to the old linux cross compile filter
AdoptOpenJDK/openjdk-build pull request #2327
Opened 2020-12-21 12:43 UTC by M-Davies

Fixes : #2325 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

2020-12-21 12:52 UTC, sxa approved these changes
Approving for test/debug purposes

2020-12-21 17:39 UTC, karianna requested changes

2020-12-21 17:39 UTC, karianna commented on pipelines/build/common/openjdk_build_pipeline.groovy
> +            filter = "OpenJDK*-jdk*_linux_*.tar.gz"
This wouldn't be correct on Mac (for Mac OS X Apple Silicon)

2020-12-22 09:51 UTC, sxa commented
Looks like it's using that `filter` as a parameter to the `tar xf` command. The behaviour has changed in https://github.com/AdoptOpenJDK/openjdk-build/pull/2117 to modify the filter used in all cases to include the `**/` prefix, so at the moment this seems a viable fix. @andrew-m-leonard Are you able to approve this given that @karianna is on vacation (and his concerns - related to if we were to cross-compile on macos/aarch64 in the future - have now been addressed)

2020-12-22 09:55 UTC, gdams approved these changes

2020-12-22 09:58 UTC, merged