lock jdk11 dragonwell to alibaba build machines (for now)
AdoptOpenJDK/openjdk-build pull request #2341
Opened 2020-12-24 16:05 UTC by sxa

Not sure why, but at the moment the vendor version string doesn't work properly when on a non-alibaba build machine. It's something we need to understand (so this should NOT close issue https://github.com/AdoptOpenJDK/openjdk-build/issues/2329#issuecomment-750916933) but this will stabilise the builds and allow us to resolve any follow-on problems for now.

Signed-off-by: Stewart X Addison <sxa@redhat.com>

2020-12-24 17:13 UTC, M-Davies requested changes

2020-12-24 17:13 UTC, M-Davies commented on pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
> +                        openj9:     'win2012&&vs2017'
```suggestion
                        openj9:     'win2012&&vs2017',
```

2020-12-27 09:33 UTC, karianna approved these changes
lgtm

2020-12-28 18:31 UTC, karianna commented
Overriding as Morgans change was committed.

2020-12-28 18:31 UTC, merged