Add default nightly testing on JDK16
AdoptOpenJDK/openjdk-build pull request #2343
Opened 2020-12-24 17:48 UTC by sxa

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2337

NOTE: I can't do the same for JDK17 for now as the jobs haven't been created, but doing this one step at a time to check machine capacity is a good thing. We could also wait until JDK15 is no longer needed before enabling JDK17 fully

Notes to reviewers:
1. PLEASE be certain I haven't made any typos in the syntax
2. PLEASE leave it for me to merge so I can do it at a time I'm paying attention to the pipelines when it first gooes through

2020-12-24 20:16 UTC, smlambert approved these changes
thanks @sxa ! 

(and I have generated jdk17 test jobs as you have mentioned them in your description to be enabled when jdk15 is done)

2020-12-25 13:45 UTC, M-Davies approved these changes
Just one non blocker. LGTM

2020-12-25 13:45 UTC, M-Davies commented on pipelines/jobs/configurations/jdk16_pipeline_config.groovy
> +                test                : 'default',
```suggestion
                test                : 'default'
```

2020-12-27 09:45 UTC, karianna requested changes

2020-12-27 09:45 UTC, karianna commented on build-farm/platform-specific-configurations/windows.sh
> +      TOOLCHAIN_VERSION="2017"
Why the drop back to 2017?

2020-12-28 18:30 UTC, karianna commented on build-farm/platform-specific-configurations/windows.sh
> +      TOOLCHAIN_VERSION="2017"
check work so I'll let this through

2020-12-28 18:30 UTC, karianna approved these changes

2020-12-28 18:30 UTC, merged