Add warning if AIX ulimit -n is too low
AdoptOpenJDK/openjdk-build pull request #2529
Opened 2021-03-15 18:07 UTC by sxa

Warn user if AIX ulimit is too low to perform the git checkout operations.
For all but JDK11, the default AIX limit of `1048575` should (only just for JDK8 - it needs 860Mb at the time of writing) work. Our jenkins users have this limit larger by defualt, but for anyone running our scripts themselves, this will warn them and pause to try and encourage to read the message otherwise they are likely to end up with things like this:
```
Cloning into 'openjdk-jdk11u'...
fatal: write error: A file cannot be larger than the value set by ulimit.
fatal: index-pack failed
```

2021-03-16 11:36 UTC, aixtools commented
Just a bit surprised by the value in the comment above, compared to the actual code.

Further, I would not stare at the (current) default - as a test value - but take a value we already know to be a minimum.
e.g. "Say unlimited is preferred, XYZ (blocks) is (approximate) minimum."

And maybe - rather than sleep(5) - a bit more 'invasive' and `press return to continue`

2021-03-16 12:23 UTC, sxa commented
> Just a bit surprised by the value in the comment above, compared to the actual code.

Can you clarify that? What value are you surprised by?

> And maybe - rather than sleep(5) - a bit more 'invasive' and press return to continue

I disagree - I don't want anything in this to be interactive.

2021-03-16 12:33 UTC, sxa commented
(Linter checks are unrelated to this PR. Not sure why it's suddenly become a problem but I'm not going to fix all of those instances in various scripts in this PR)

2021-03-23 09:46 UTC, karianna requested changes

2021-03-23 09:46 UTC, karianna commented on build-farm/platform-specific-configurations/aix.sh
> +# AIX default ulimit is frequently less than we need to clone the LTS JDK repositories
Why the value of 2097150?

2021-03-28 12:29 UTC, karianna approved these changes

2021-03-28 12:50 UTC, smlambert approved these changes
LGTM

2021-03-29 11:32 UTC, merged