make-adopt-build-farm: Use arm instead of armv7l
AdoptOpenJDK/openjdk-build pull request #2541
Opened 2021-03-20 12:27 UTC by sxa

Found while verifying https://github.com/AdoptOpenJDK/openjdk-build/pull/2539

While we use `armv7l` for `OS_ARCHITECTURE`, the `ARCHITECTURE` variables should be `arm` for arm32 builds.

Signed-off-by: Stewart X Addison <sxa@redhat.com>

2021-03-20 13:45 UTC, M-Davies requested changes
Linter issues

2021-03-22 13:43 UTC, sxa commented
> Linter issues

Those seem to be linter issue that have nothing to do with this PR - I would suggest they need to be part of a separate PR as it will make it less obvious what was really changed to fix the problem that this PR is addressing.

2021-03-22 13:48 UTC, M-Davies approved these changes

2021-03-22 14:31 UTC, sxa commented
(Raised https://github.com/AdoptOpenJDK/openjdk-build/issues/2542 for the linter problems)

2021-03-23 12:39 UTC, andrew-m-leonard approved these changes

2021-03-23 12:43 UTC, merged